### ISSUE TITLE
Hello, I cannot edit my bios flow the url you gived 

### ISSUE THREAD

**Issue by loadnl** [TiToMoskito/Razer-Blade-Base-2020-Hackintosh#1]
how do you solved this?  I am sorry for my poor English

**Comment by TiToMoskito** [comment]
You need an CH340 Bios Flasher, like this one https://de.aliexpress.com/i/32764268709.html

**Comment by loadnl** [comment]
Thank you for your answer and your EFI ! I find that I have not edited some bios items but I can run Catalina successful.
