### ISSUE TITLE
BIOS Dump

### ISSUE THREAD

**Issue by jt1900jt** [TiToMoskito/Razer-Blade-Base-2020-Hackintosh#2]
I have this exact same razer blade 2020 base model and I have bricked my laptop while flashing a modded BIOS via hardware programmer. Additionally my backups seem to be corrupt. I'm wondering if @TiToMoskito or anyone else could upload a BIOS dump for me to try and flash to revive my machine. Thanks in advance.

**Comment by TiToMoskito** [comment]
This are my clean backup rom files.

v1.04
[original_104.zip](https://github.com/TiToMoskito/Razer-Blade-Base-2020-Hackintosh/files/5753524/original_104.zip)

v1.06
[original_106.zip](https://github.com/TiToMoskito/Razer-Blade-Base-2020-Hackintosh/files/5753525/original_106.zip)
